/* Copyright (c) 2016 - deemon by Griefer@Work                                    *
 *                                                                                *
 * Permission is hereby granted, free of charge, to any person obtaining a copy   *
 * of this software and associated documentation files (the "Software"), to deal  *
 * in the Software without restriction, including without limitation the rights   *
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell      *
 * copies of the Software, and to permit persons to whom the Software is          *
 * furnished to do so, subject to the following conditions:                       *
 *                                                                                *
 * The above copyright notice and this permission notice shall be included in all *
 * copies or substantial portions of the Software.                                *
 *                                                                                *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR     *
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,       *
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE    *
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER         *
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,  *
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  *
 * SOFTWARE.                                                                      *
 */

// This is an autogenerated file!!!
// To edit this file, please modify "__codegen/make_feature_strings.dee"

#if DEE_CONFIG_API_HAVE_HASHMAP_EXPORTS
"api_hashmap_exports\0"
#endif
#if DEE_CONFIG_API_HAVE_HASHSET_EXPORTS
"api_hashset_exports\0"
#endif
#if DEE_CONFIG_API_HAVE_MATH_EXPORTS
"api_math_exports\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_ALIAS
"language_alias\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_ARRAYS
"language_arrays\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_ALLOCA
"language_builtin_alloca\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_BOUND
"language_builtin_bound\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_BREAKPOINT
"language_builtin_breakpoint\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_CHOOSE_EXPR
"language_builtin_choose_expr\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_CONSTANT_P
"language_builtin_constant_p\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_DEAD
"language_builtin_dead\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_DEX
"language_builtin_dex\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_EXISTS
"language_builtin_exists\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_EXPECT
"language_builtin_expect\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_EXPRAST
"language_builtin_exprast\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_HELP
"language_builtin_help\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_NOEFFECT
"language_builtin_noeffect\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_NOEXCEPT
"language_builtin_noexcept\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_NOOP
"language_builtin_noop\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_NORETURN
"language_builtin_noreturn\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_OFFSETOF
"language_builtin_offsetof\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_PREDICTABLE
"language_builtin_predictable\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_TYPEOF
"language_builtin_typeof\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_TYPES_COMPATIBLE_P
"language_builtin_types_compatible_p\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_UNREACHABLE
"language_builtin_unreachable\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_BUILTIN_UNUSED
"language_builtin_unused\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_CELL_SYNTAX
"language_cell_syntax\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_CLASS_TYPES
"language_class_types\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_ELIF_ELSE_IF_ALIAS
"language_elif_else_if_alias\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_ENUM_TYPES
"language_enum_types\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_EXCEPTIONS
"language_exceptions\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_EXPR_STATEMENTS
"language_expr_statements\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_EXTERN
"language_extern\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_FOREIGNFUNCTION
"language_foreignfunction\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_FOREIGNFUNCTIONCLOSURE
"language_foreignfunctionclosure\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_GENERATORS
"language_generators\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_IF_EXISTS
"language_if_exists\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_IF_EXPRESSION
"language_if_expression\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_LAMBDA_SYNTAX
"language_lambda_syntax\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_NEWDELETE
"language_newdelete\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_OPERATOR_FUNCTIONS
"language_operator_functions\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_POINTERS
"language_pointers\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_RELAXED_COMMA_LIST
"language_relaxed_comma_list\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_STACK_VARIABLES
"language_stack_variables\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_STATIC_IF
"language_static_if\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_STRUCT_TYPES
"language_struct_types\0"
#endif
#if DEE_CONFIG_LANGUAGE_HAVE_SWITCH_EXPRESSION
"language_switch_expression\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_ARRAYS
"runtime_arrays\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_AUTO_UNC
"runtime_auto_unc\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_BUILTIN_ALLOCA
"runtime_builtin_alloca\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_BUILTIN_BOUND
"runtime_builtin_bound\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_BUILTIN_BREAKPOINT
"runtime_builtin_breakpoint\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_BUILTIN_HELP
"runtime_builtin_help\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_CLASS_STATIC_VTABLE
"runtime_class_static_vtable\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_CLASS_TYPES
"runtime_class_types\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_DOCSTRINGS
"runtime_docstrings\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_EXCEPTIONS
"runtime_exceptions\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_EXIT
"runtime_exit\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_EXTERN
"runtime_extern\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_FOREIGNFUNCTION
"runtime_foreignfunction\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_FOREIGNFUNCTIONCLOSURE
"runtime_foreignfunctionclosure\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_LVALUE_OPS_SIGNAL_PROTECTED
"runtime_lvalue_ops_signal_protected\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_NEWDELETE
"runtime_newdelete\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_POINTERS
"runtime_pointers\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_PROCESS
"runtime_process\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_RECONFIGURE_ENV
"runtime_reconfigure_env\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_SIGNAL_HANDLERS
"runtime_signal_handlers\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_SOCKET_API
"runtime_socket_api\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_STACKLIMIT_CHECKS
"runtime_stacklimit_checks\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_STRICT_INTERNAL_INTEGRAL_TYPENAMES
"runtime_strict_internal_integral_typenames\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_UPDATE_CHECK
"runtime_update_check\0"
#endif
#if DEE_CONFIG_RUNTIME_HAVE_VFS
"runtime_vfs\0"
#endif
